export const localStorageProperties = {
    Token: "LOCALSTORAGE_TOKEN"
}

export const FETCH_TASKS_START   = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const FETCH_MORE_TASKS_START   = 'FETCH_MORE_TASKS_START';
export const FETCH_MORE_TASKS_SUCCESS = 'FETCH_MORE_TASKS_SUCCESS';
export const FETCH_MORE_TASKS_FAILURE = 'FETCH_MORE_TASKS_FAILURE';

export const UPDATE_TASK_START   = 'UPDATE_TASK_START';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';

export const DELETE_TASK_START   = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const CREATE_TASK_START   = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';